### ISSUE TITLE
SVG and Extra Blank

### ISSUE THREAD

**Issue by aress31** [pemtajo/badge-readme#14]
Just wondering if it could be possible to use `svg` version of certificate badges rather than `png`. As `svg` would be crisper and scalable from `0` to `infinite` **without quality loss**.

Also, I noticed an extra - unnecessary - line break (OCD alert), see:

```
<!--START_SECTION:badges-->

[![Offensive Security Web Expert (OSWE)](https://images.credly.com/size/96x96/images/c8c413ce-fce6-4b61-89e6-6a1b9f1e358a/AWAE-OSWE-badge.png)](http://www.credly.com/badges/654e5bc5-0fbe-4d17-ab44-93331a1fc365 "Offensive Security Web Expert (OSWE)")
[![Offensive Security Certified Professional (OSCP)](https://images.credly.com/size/96x96/images/e3c9ad3c-b142-45ae-bb2b-2f19ff2b742a/PWK-OSCP-badge.png)](http://www.credly.com/badges/1064ddf3-8305-4f17-bc79-72f1e9f86408 "Offensive Security Certified Professional (OSCP)")
<!--END_SECTION:badges-->
```

**Comment by pemtajo** [comment]
I don't know if it's possible to receive the SVG, because the project is not for an API, but a web scrap on the Credly page.

I check again and can't find any information about SVG. Since I don't work at Credly, I only index public information.

I'll close this issue because I joined your PR and I don't have much to do about SVG. But I'll go by history, maybe things will change in the future.

thanks for the contribution
